### ISSUE TITLE
Freeway ModuleNotFoundError: No module named 'checkmac' and No module named 'netaddr'

### ISSUE THREAD

**Issue by falcolnic** [FLOCK4H/Freeway#3]
**Describe the bug**
Cant run script

**To Reproduce**
So i tried 2 times.
In the first one i used sudo pip install 3way and i get an error 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/FreewayTools/monitor.py", line 15, in <module>
    from FreewayTools.checkmac import check_manufacturer
  File "/usr/local/lib/python3.10/dist-packages/FreewayTools/checkmac.py", line 2, in <module>
    from netaddr import EUI
ModuleNotFoundError: No module named 'netaddr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/Freeway", line 16, in <module>
    from FreewayTools.colors import cprint, iprint, wprint, cinput, ColorCodes
  File "/usr/local/lib/python3.10/dist-packages/FreewayTools/__init__.py", line 4, in <module>
    from .monitor import Monitor
  File "/usr/local/lib/python3.10/dist-packages/FreewayTools/monitor.py", line 17, in <module>
    from checkmac import check_manufacturer
ModuleNotFoundError: No module named 'checkmac'
```

Then i deleted all, and used second way to download through clonning, and get the same error.

Thats it!
How to fix it?

**Comment by FLOCK4H** [comment]
Please try this,

**Manually install Freeway using:**

```
$ sudo pip install netaddr
$ sudo pip install .
```
